"use client";
import Link from "next/link";
import type { OfferDTO, RoomDTO, SearchDTO } from "../schema";
import { AttributeSummary } from "./activity-attributes";
const statusLabels = { active: "Ищем компанию", filled: "Компания собралась", closed: "Поиск остановлен", expired: "Время поиска истекло" };
export function SearchCard({ search, busy, onEdit, onCommand }: { search: SearchDTO; busy: boolean; onEdit: () => void; onCommand: (type: "stop" | "extend") => void }) {
  return <article className="intent-card intent-search"><div className="intent-card-heading"><h3>{search.activityLabel}</h3><span className={`intent-state intent-state-${search.status}`}>{statusLabels[search.status]}</span></div><p>{search.timeHint}</p><div className="intent-counts"><span>{search.joinedCount} / {search.capacity} мест занято</span><span>{search.offeredCount} предложений</span><span>{search.acceptedCount} приняли</span></div>{search.existingPeople > 1 && <p className="intent-muted">{search.existingPeople - 1} мест — ваши участники вне Veya.</p>}{search.status === "active" && <><p className="intent-muted">Совместимых намерений в последней проверке: {search.compatibleCount}. Предложения появятся по мере новых совпадений.</p><div className="intent-actions"><button className="intent-text-button" disabled={busy} onClick={onEdit}>Изменить поиск</button><button className="intent-text-button" disabled={busy} onClick={() => onCommand("extend")}>Продлить на час</button><button className="intent-text-button" disabled={busy} onClick={() => onCommand("stop")}>Остановить</button></div></>}{search.roomKey && <Link className="intent-button" href={`/room/${encodeURIComponent(search.roomKey)}`}>Открыть комнату</Link>}</article>;
}
export function OfferCard({ offer, busy, onRespond }: { offer: OfferDTO; busy: boolean; onRespond: (action: "accept" | "decline") => void }) {
  return <article className="intent-card intent-offer"><p className="intent-eyebrow">Есть совпадение</p><h3>{offer.activityLabel}</h3><p>{offer.timeHint}</p><AttributeSummary attributes={offer.attributes} /><p className="intent-muted">Нужно ещё участников: {offer.neededPeople}. Вы вступите в комнату только после вашего согласия и заполнения группы.</p><div className="intent-actions"><button className="intent-button" disabled={busy} onClick={() => onRespond("accept")}>Я в деле</button><button className="intent-text-button" disabled={busy} onClick={() => onRespond("decline")}>Не сейчас</button><Link className="intent-text-button" href={`/offer/${encodeURIComponent(offer.publicKey)}`}>Подробности</Link></div></article>;
}
export function RoomCard({ room }: { room: RoomDTO }) {
  return <Link className="intent-card intent-room-card" href={`/room/${encodeURIComponent(room.publicKey)}`}><div className="intent-card-heading"><h3>{room.activityLabel}</h3><span className="intent-state">{room.status === "completed" ? "Завершено" : room.status === "archived" ? "В архиве" : room.status === "closed" ? "Закрыто" : "Компания собралась"}</span></div><p>{room.members.map((member) => member.isMine ? "Вы" : member.alias).join(" · ")}</p><p className="intent-muted">{room.joinedCount} / {room.capacity} участников{room.externalCount ? ` · ${room.externalCount} вне Veya` : ""}</p><span className="intent-text-button">Открыть комнату →</span></Link>;
}
