import { afterAll, beforeAll, beforeEach, expect, it } from 'vitest';
import { startTestDatabase } from '../support/postgres';
import { applyMigrations } from '@/lib/db/migrations';
import { socialActor, seekingInput, forbiddenKeys } from '../support/social';
import { IntentProductService } from '@/features/intent-product/service';
import { RoomService } from '@/features/intent-product/rooms';
import { processIntentJobs } from '@/features/intent-product/worker';
import { searchDraftSchema } from '@/features/intent-product/schema';
let c: Awaited<ReturnType<typeof startTestDatabase>>;
beforeAll(async () => { c = await startTestDatabase(); await applyMigrations(c.db); });
afterAll(async () => { if (c)
    await c.stop(); });
beforeEach(async () => { await c.db.query('TRUNCATE social_profiles CASCADE'); });
const draft = (extra = {}) => searchDraftSchema.parse({ seeking: seekingInput(), neededPeople: 1, existingPeople: 1, attributes: {}, timezone: 'UTC', ...extra });
async function setup() { const a = await socialActor(c.db, 'Owner private'), b = await socialActor(c.db, 'Target private'), third = await socialActor(c.db, 'Third private'); const service = new IntentProductService(c.db); const search = await service.create(a.token, { draft: draft(), consent: true }); await processIntentJobs(c.db); return { a, b, third, service, search }; }
it('atomically creates a post, lobby, owner and durable job; no invented members', async () => { const a = await socialActor(c.db, 'Owner'); const s = await new IntentProductService(c.db).create(a.token, { draft: draft({ seeking: seekingInput({ activityKey: 'dota2', interactionMode: 'online', city: null, format: 'group', groupSize: 5 }), existingPeople: 4 }), consent: true }); expect(s).toMatchObject({ capacity: 5, joinedCount: 4, acceptedCount: 0 }); expect((await c.db.query('SELECT * FROM social_lobby_members')).rows).toHaveLength(1); expect((await c.db.query('SELECT * FROM social_intent_jobs')).rows).toHaveLength(1); });
it('deduplicates offers and admits exactly one last-slot accept across concurrent transactions', async () => { const { a, b, third, service, search } = await setup(); const bo = (await service.offers(b.token))[0]!, co = (await service.offers(third.token))[0]!; expect(bo).toBeTruthy(); expect(co).toBeTruthy(); expect(forbiddenKeys(bo)).toEqual([]); await processIntentJobs(c.db); expect((await service.offers(b.token))).toHaveLength(1); const result = await Promise.allSettled([service.respond(b.token, bo.publicKey, { action: 'accept' }), service.respond(third.token, co.publicKey, { action: 'accept' })]); expect(result.filter(r => r.status === 'fulfilled')).toHaveLength(1); const s = await service.get(a.token, search.publicKey); expect(s).toMatchObject({ status: 'filled', joinedCount: 2, acceptedCount: 1 }); expect((await c.db.query('SELECT * FROM social_rooms')).rows).toHaveLength(1); const winner = result.findIndex(r => r.status === 'fulfilled'); const actor = winner === 0 ? b : third, offer = winner === 0 ? bo : co; expect(await service.respond(actor.token, offer.publicKey, { action: 'accept' })).toMatchObject({ status: 'accepted', roomKey: s.roomKey }); });
it('checks room membership on every call and uses unrelated Incognito room identities', async () => { const { a, b, third, service } = await setup(); const offer = (await service.offers(b.token))[0]!; const accepted = await service.respond(b.token, offer.publicKey, { action: 'accept' }); const rooms = new RoomService(c.db), key = accepted.roomKey!; const view = await rooms.get(b.token, key); expect(forbiddenKeys(view)).toEqual([]); expect(JSON.stringify(view)).not.toMatch(/Owner private|Target private/); await expect(rooms.get(third.token, key)).rejects.toMatchObject({ code: 'NOT_FOUND' }); await expect(rooms.send(third.token, key, { text: 'IDOR' })).rejects.toMatchObject({ code: 'NOT_FOUND' }); await rooms.send(a.token, key, { text: 'hello' }); expect((await rooms.messages(b.token, key)).messages[0]).toMatchObject({ text: 'hello', isMine: false }); await rooms.remove(b.token, key, { memberKey: view.members.find(m => m.isMine)!.publicKey }); await expect(rooms.send(b.token, key, { text: 'stale' })).rejects.toMatchObject({ code: 'NOT_FOUND' }); await expect(rooms.send(a.token, key, { text: 'closed' })).rejects.toMatchObject({ code: 'CONFLICT' }); });
it('stop cancels pending offers and prevents new delivery', async () => { const { a, b, service, search } = await setup(); await service.command(a.token, search.publicKey, { type: 'stop' }); expect((await service.offers(b.token))[0]).toMatchObject({ status: 'cancelled' }); expect((await processIntentJobs(c.db)).offered).toBe(0); await expect(service.respond(b.token, (await service.offers(b.token))[0]!.publicKey, { action: 'accept' })).rejects.toMatchObject({ code: 'CONFLICT' }); });
it('rejects expired offers and rechecks recipient post privacy/capability and preference state', async () => { const { b, service } = await setup(); const offer = (await service.offers(b.token))[0]!; await c.db.query("UPDATE social_candidate_offers SET created_at=clock_timestamp()-interval '2 hours',expires_at=clock_timestamp()-interval '1 hour' WHERE public_key=$1", [offer.publicKey]); expect(await service.offer(b.token, offer.publicKey)).toMatchObject({ status: 'expired' }); await expect(service.respond(b.token, offer.publicKey, { action: 'accept' })).rejects.toMatchObject({ code: 'CONFLICT' }); });
it.each(['post-closed', 'recipient-connect', 'recipient-suspended', 'owner-suspended', 'blocked', 'disabled-offers'])('rechecks %s before accepting delivery already made', async (kind) => { const { a, b, service } = await setup(); const offer = (await service.offers(b.token))[0]!; const ids = (await c.db.query<{
    id: string;
}>('SELECT id FROM social_profiles ORDER BY created_at')).rows; if (kind === 'post-closed')
    await c.db.query("UPDATE seeking_posts SET status='closed' WHERE public_key=$1", [b.post.publicKey]); if (kind === 'recipient-connect')
    await c.db.query('UPDATE social_profiles SET can_connect=false WHERE id=$1', [ids[1]!.id]); if (kind === 'recipient-suspended')
    await c.db.query("UPDATE social_profiles SET moderation_status='suspended' WHERE id=$1", [ids[1]!.id]); if (kind === 'owner-suspended')
    await c.db.query("UPDATE social_profiles SET moderation_status='suspended' WHERE id=$1", [ids[0]!.id]); if (kind === 'blocked')
    await c.db.query('INSERT INTO social_blocks(blocker_profile_id,blocked_profile_id) VALUES($1,$2)', [ids[0]!.id, ids[1]!.id]); if (kind === 'disabled-offers')
    await service.savePreferences(b.token, { offersEnabled: false, timezone: 'UTC', quietHours: null, activities: [] }); await expect(service.respond(b.token, offer.publicKey, { action: 'accept' })).rejects.toBeTruthy(); expect((await service.get(a.token, (await c.db.query<{
    public_key: string;
}>('SELECT public_key FROM social_action_searches')).rows[0]!.public_key).catch(() => null))?.acceptedCount ?? 0).toBe(0); expect((await c.db.query('SELECT * FROM social_rooms')).rows).toHaveLength(0); });
it('freezes minimized report evidence and preserves it through profile deletion', async () => { const { a, b, service } = await setup(); const accepted = await service.respond(b.token, (await service.offers(b.token))[0]!.publicKey, { action: 'accept' }); const rooms = new RoomService(c.db), view = await rooms.get(a.token, accepted.roomKey!); await rooms.send(b.token, view.publicKey, { text: 'Reported sample' }); const target = view.members.find(m => !m.isMine)!; await rooms.report(a.token, view.publicKey, { memberKey: target.publicKey, reason: 'harassment' }); const report = (await c.db.query<{
    id: string;
    evidence: unknown;
}>('SELECT id,evidence FROM social_reports')).rows[0]!; expect(JSON.stringify(report.evidence)).toContain('Reported sample'); expect(forbiddenKeys(report.evidence)).toEqual([]); await expect(c.db.query("UPDATE social_reports SET evidence='{}' WHERE id=$1", [report.id])).rejects.toMatchObject({ code: '23514' }); const { ProfileDeletionService } = await import('@/features/social/deletion'); await new ProfileDeletionService(c.db).delete(b.token, { confirmation: 'DELETE' }); expect((await c.db.query('SELECT text FROM social_room_messages')).rows).toHaveLength(0); expect((await c.db.query<{
    evidence: unknown;
}>('SELECT evidence FROM social_reports')).rows[0]!.evidence).toEqual(report.evidence); await expect(rooms.send(a.token, view.publicKey, { text: 'unsafe' })).rejects.toMatchObject({ code: 'CONFLICT' }); });
it('blocks room contact and invalidates duplicate acceptance authority', async () => { const { a, b, service } = await setup(); const offer = (await service.offers(b.token))[0]!, accepted = await service.respond(b.token, offer.publicKey, { action: 'accept' }); const rooms = new RoomService(c.db), view = await rooms.get(a.token, accepted.roomKey!); await rooms.block(a.token, view.publicKey, { memberKey: view.members.find(m => !m.isMine)!.publicKey }); await expect(rooms.send(b.token, view.publicKey, { text: 'blocked' })).rejects.toMatchObject({ code: 'NOT_FOUND' }); await expect(service.respond(b.token, offer.publicKey, { action: 'accept' })).rejects.toMatchObject({ code: 'CONFLICT' }); });
it('completion archives history and closes sends without pretending attendance', async () => { const { a, b, service } = await setup(); const accepted = await service.respond(b.token, (await service.offers(b.token))[0]!.publicKey, { action: 'accept' }); const rooms = new RoomService(c.db), key = accepted.roomKey!; await expect(rooms.transition(b.token, key, { status: 'completed' })).rejects.toMatchObject({ code: 'FORBIDDEN' }); expect(await rooms.transition(a.token, key, { status: 'completed' })).toMatchObject({ status: 'completed' }); expect(await rooms.transition(a.token, key, { status: 'archived' })).toMatchObject({ status: 'archived' }); await expect(rooms.send(a.token, key, { text: 'ended' })).rejects.toMatchObject({ code: 'CONFLICT' }); });
it('updates invalidate pending offers and replace the durable lease nonce', async () => { const { a, b, service, search } = await setup(); const old = (await service.offers(b.token))[0]!; await c.db.query("UPDATE social_intent_jobs SET status='processing',lease_key='AAAAAAAAAAAAAAAAAAAAAAAA',lease_until=clock_timestamp()+interval '5 minutes' WHERE search_id=(SELECT id FROM social_action_searches WHERE public_key=$1)", [search.publicKey]); await service.update(a.token, search.publicKey, { draft: draft(), consent: true }); expect(await service.offer(b.token, old.publicKey)).toMatchObject({ status: 'cancelled' }); expect((await c.db.query('SELECT revision FROM social_action_searches')).rows).toEqual([{ revision: 2 }]); await expect(service.respond(b.token, old.publicKey, { action: 'accept' })).rejects.toMatchObject({ code: 'CONFLICT' }); });
it('protects plain-text pagination cursors against cross-room references', async () => { const { a, b, service } = await setup(); const accepted = await service.respond(b.token, (await service.offers(b.token))[0]!.publicKey, { action: 'accept' }); const rooms = new RoomService(c.db), key = accepted.roomKey!; for (let i = 0; i < 4; i++)
    await rooms.send(a.token, key, { text: 'message ' + i }); const page = await rooms.messages(b.token, key, { limit: 2 }); expect(page.messages.map(m => m.text)).toEqual(['message 2', 'message 3']); expect(page.nextBefore).toBeTruthy(); expect((await rooms.messages(b.token, key, { limit: 2, before: page.nextBefore! })).messages.map(m => m.text)).toEqual(['message 0', 'message 1']); await expect(rooms.messages(b.token, key, { before: 'AAAAAAAAAAAAAAAAAAAAAAAA' })).rejects.toMatchObject({ code: 'NOT_FOUND' }); await expect(rooms.messages(b.token, key, { limit: 51 })).rejects.toBeTruthy(); });
it('returns a quiet-hour candidate to the durable queue and honors explicit offers preferences', async () => { const a = await socialActor(c.db, 'Owner'), b = await socialActor(c.db, 'Quiet'); const hour = new Date().getUTCHours(); const service = new IntentProductService(c.db); await service.savePreferences(b.token, { offersEnabled: true, timezone: 'UTC', quietHours: { startHour: hour, endHour: (hour + 1) % 24 }, activities: [] }); await service.create(a.token, { draft: draft(), consent: true }); expect(await service.offers(b.token)).toEqual([]); expect((await c.db.query('SELECT status,attempts FROM social_intent_jobs')).rows).toEqual([{ status: 'pending', attempts: 0 }]); await service.savePreferences(b.token, { offersEnabled: true, timezone: 'UTC', quietHours: null, activities: [] }); await c.db.query('UPDATE social_intent_jobs SET available_at=clock_timestamp()'); expect((await processIntentJobs(c.db)).offered).toBe(1); expect(await service.offers(b.token)).toHaveLength(1); });
it('handles concurrent job claims once and leaves aborted jobs untouched', async () => { const a = await socialActor(c.db, 'Owner'), service = new IntentProductService(c.db); await service.create(a.token, { draft: draft(), consent: true }); const b = await socialActor(c.db, 'Future'); await c.db.query("UPDATE social_intent_jobs SET status='pending',available_at=clock_timestamp(),attempts=0,finished_at=NULL"); const controller = new AbortController(); controller.abort(); expect(await processIntentJobs(c.db, { signal: controller.signal })).toMatchObject({ claimed: 0, offered: 0 }); const result = await Promise.all([processIntentJobs(c.db), processIntentJobs(c.db)]); expect(result.reduce((n, r) => n + r.claimed, 0)).toBe(1); expect(result.reduce((n, r) => n + r.offered, 0)).toBe(1); expect(await service.offers(b.token)).toHaveLength(1); });
it('enforces capacity and cross-lobby consent in PostgreSQL as well as services', async () => { const { a, b, third, service } = await setup(); const accepted = await service.respond(b.token, (await service.offers(b.token))[0]!.publicKey, { action: 'accept' }); const lobby = (await c.db.query<{
    lobby_id: string;
}>('SELECT lobby_id FROM social_rooms WHERE public_key=$1', [accepted.roomKey])).rows[0]!.lobby_id; const target = (await c.db.query<{
    id: string;
}>('SELECT p.id FROM social_profiles p JOIN social_profile_bindings b ON b.profile_id=p.id JOIN seeking_posts s ON s.profile_id=p.id WHERE s.public_key=$1', [third.post.publicKey])).rows[0]!.id; await expect(c.db.query("INSERT INTO social_lobby_members(lobby_id,profile_id,public_key,alias,avatar_seed,privacy_mode) VALUES($1,$2,'AAAAAAAAAAAAAAAAAAAAAAAA','Fake','aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa','INCOGNITO')", [lobby, target])).rejects.toMatchObject({ code: '23514' }); const source = (await service.list(a.token))[0]!; expect(source.joinedCount).toBe(2); });
it('generates unrelated room-only aliases and seeds even for the same registered members', async () => { const { a, b, service } = await setup(); const accepted = await service.respond(b.token, (await service.offers(b.token))[0]!.publicKey, { action: 'accept' }); const rooms = new RoomService(c.db), first = await rooms.get(a.token, accepted.roomKey!); await rooms.transition(a.token, first.publicKey, { status: 'completed' }); await service.create(a.token, { draft: draft(), consent: true }); const pending = (await service.offers(b.token)).find(o => o.status === 'pending')!; const secondAccept = await service.respond(b.token, pending.publicKey, { action: 'accept' }); const second = await rooms.get(a.token, secondAccept.roomKey!); for (const isMine of [true, false]) {
    const one = first.members.find(m => m.isMine === isMine)!, two = second.members.find(m => m.isMine === isMine)!;
    expect(two.publicKey).not.toBe(one.publicKey);
    expect(two.alias).not.toBe(one.alias);
    expect(two.avatarSeed).not.toBe(one.avatarSeed);
} });
it('keeps retained room report shells when the search owner deletes their profile', async () => {
 const {a,b,service}=await setup();const accepted=await service.respond(b.token,(await service.offers(b.token))[0]!.publicKey,{action:'accept'});const rooms=new RoomService(c.db),view=await rooms.get(b.token,accepted.roomKey!);await rooms.send(a.token,view.publicKey,{text:'Owner evidence'});await rooms.report(b.token,view.publicKey,{memberKey:view.members.find(m=>!m.isMine)!.publicKey,reason:'spam'});const evidence=(await c.db.query('SELECT evidence FROM social_reports')).rows[0]!.evidence;const {ProfileDeletionService}=await import('@/features/social/deletion');await new ProfileDeletionService(c.db).delete(a.token,{confirmation:'DELETE'});expect((await c.db.query('SELECT post_id,draft,status FROM social_action_searches')).rows).toEqual([{post_id:null,draft:{},status:'closed'}]);expect((await c.db.query('SELECT evidence FROM social_reports')).rows[0]!.evidence).toEqual(evidence);expect(await rooms.get(b.token,view.publicKey)).toMatchObject({status:'closed',members:[{isMine:true}]});
});
it('creates one shared Planit under concurrent member requests', async () => {
 const {a,b,service}=await setup();const accepted=await service.respond(b.token,(await service.offers(b.token))[0]!.publicKey,{action:'accept'});const rooms=new RoomService(c.db),key=accepted.roomKey!;const [one,two]=await Promise.all([rooms.plan(a.token,key),rooms.plan(b.token,key)]);expect(one).toEqual(two);expect((await c.db.query('SELECT plan_intent_id FROM social_rooms')).rows[0]!.plan_intent_id).toBeTruthy();expect((await rooms.get(a.token,key)).planSlug).toBe(one.slug);
});
it('leaves a reclaimed worker lease untouched after waiting for profile locks', async()=>{
 const a=await socialActor(c.db,'Owner'),service=new IntentProductService(c.db);await service.create(a.token,{draft:draft(),consent:true});await socialActor(c.db,'Future');await c.db.query("UPDATE social_intent_jobs SET status='pending',available_at=clock_timestamp(),attempts=0");let changed=false;const db:typeof c.db={query:(sql,args)=>c.db.query(sql,args),close:async()=>{},transaction:work=>c.db.transaction(tx=>work({query:async(sql,args)=>{if(!changed&&sql.includes('pg_advisory_xact_lock')){changed=true;await tx.query("UPDATE social_intent_jobs SET lease_key='BBBBBBBBBBBBBBBBBBBBBBBB',lease_until=clock_timestamp()+interval '5 minutes' WHERE status='processing'");}return tx.query(sql,args);}}))};expect(await processIntentJobs(db)).toMatchObject({claimed:1,completed:0,offered:0});expect((await c.db.query('SELECT status,lease_key FROM social_intent_jobs')).rows).toEqual([{status:'processing',lease_key:'BBBBBBBBBBBBBBBBBBBBBBBB'}]);expect((await c.db.query('SELECT * FROM social_candidate_offers')).rows).toHaveLength(0);
});
it('bounds failed job retries and persists only fixed failure codes', async()=>{
 const a=await socialActor(c.db,'Owner'),service=new IntentProductService(c.db);await service.create(a.token,{draft:draft(),consent:true});await socialActor(c.db,'Future');await c.db.query("UPDATE social_intent_jobs SET status='pending',available_at=clock_timestamp(),attempts=0");const db:typeof c.db={query:(sql,args)=>c.db.query(sql,args),close:async()=>{},transaction:work=>c.db.transaction(tx=>work({query:async(sql,args)=>{if(sql.includes('SELECT t.id,t.profile_id'))throw new Error('Do not store authored text or secrets');return tx.query(sql,args);}}))};expect(await processIntentJobs(db)).toMatchObject({retried:1,offered:0});await c.db.query('UPDATE social_intent_jobs SET attempts=4,available_at=clock_timestamp()');expect(await processIntentJobs(db)).toMatchObject({failed:1,offered:0});expect((await c.db.query('SELECT status,attempts,failure_code,lease_key FROM social_intent_jobs')).rows).toEqual([{status:'failed',attempts:5,failure_code:'MATCHING_FAILED',lease_key:null}]);
});
it('truthfully cancels a consented waiting offer when the unfinished lobby stops', async()=>{
 const a=await socialActor(c.db,'Owner'),b=await socialActor(c.db,'Group target','INCOGNITO',{format:'group',groupSize:null});const service=new IntentProductService(c.db);const search=await service.create(a.token,{draft:draft({neededPeople:2,seeking:seekingInput({format:'group',groupSize:3})}),consent:true});const offer=(await service.offers(b.token))[0]!;expect(await service.respond(b.token,offer.publicKey,{action:'accept'})).toMatchObject({status:'accepted',roomKey:null});expect((await c.db.query('SELECT status FROM social_lobbies')).rows).toEqual([{status:'forming'}]);await service.command(a.token,search.publicKey,{type:'stop'});expect(await service.offer(b.token,offer.publicKey)).toMatchObject({status:'cancelled',roomKey:null});expect((await c.db.query('SELECT status FROM social_lobbies')).rows).toEqual([{status:'closed'}]);await expect(service.respond(b.token,offer.publicKey,{action:'accept'})).rejects.toMatchObject({code:'CONFLICT'});
});
it('limits delivery to five offers in a claimed batch and respects the pending budget', async()=>{
 const a=await socialActor(c.db,'Owner');for(let i=0;i<6;i++)await socialActor(c.db,'Target '+i);const service=new IntentProductService(c.db),search=await service.create(a.token,{draft:draft(),consent:true});expect((await service.get(a.token,search.publicKey)).offeredCount).toBe(5);const {enqueueIntentJob}=await import('@/features/intent-product/worker');await c.db.transaction(async tx=>{const id=(await tx.query<{id:string}>('SELECT id FROM social_action_searches WHERE public_key=$1',[search.publicKey])).rows[0]!.id;await enqueueIntentJob(tx,id);});expect(await processIntentJobs(c.db)).toMatchObject({offered:1});expect((await service.get(a.token,search.publicKey)).offeredCount).toBe(6);
});
it('honors stronger Incognito post privacy for Open profiles inside rooms',async()=>{
 const a=await socialActor(c.db,'Open visible owner','OPEN'),b=await socialActor(c.db,'Open visible target','OPEN',{privacyMode:'INCOGNITO'});const service=new IntentProductService(c.db);await service.create(a.token,{draft:draft({seeking:seekingInput({privacyMode:'INCOGNITO'})}),consent:true});const accepted=await service.respond(b.token,(await service.offers(b.token))[0]!.publicKey,{action:'accept'});const room=await new RoomService(c.db).get(a.token,accepted.roomKey!);expect(JSON.stringify(room)).not.toMatch(/Open visible owner|Open visible target/);expect(room.members.every(m=>m.alias.startsWith('Тихий '))).toBe(true);
});
it('closes a search and its pending offers when the linked legacy post stops',async()=>{
 const {a,b,service,search}=await setup();const linked=(await c.db.query<{post_id:string}>('SELECT post_id FROM social_action_searches WHERE public_key=$1',[search.publicKey])).rows[0]!.post_id;await c.db.query("UPDATE seeking_posts SET status='closed' WHERE id=$1",[linked]);await c.db.query("UPDATE social_intent_jobs SET status='pending',attempts=0,available_at=clock_timestamp(),lease_key=NULL,lease_until=NULL");await processIntentJobs(c.db);expect(await service.get(a.token,search.publicKey)).toMatchObject({status:'closed'});expect((await service.offers(b.token))[0]).toMatchObject({status:'cancelled'});
});

it('replaces cancelled prior-revision offers after a confirmed search update while preserving declines',async()=>{
 const {a,b,third,service,search}=await setup();
 const old=(await service.offers(b.token))[0]!,passed=(await service.offers(third.token))[0]!;
 await service.respond(third.token,passed.publicKey,{action:'decline'});
 await service.update(a.token,search.publicKey,{draft:draft(),consent:true});
 const replacements=(await service.offers(b.token)).filter(o=>o.status==='pending');
 expect(replacements).toHaveLength(1);expect(replacements[0]!.publicKey).not.toBe(old.publicKey);
 expect(await service.offer(b.token,old.publicKey)).toMatchObject({status:'cancelled'});
 expect((await service.offers(third.token)).filter(o=>o.status==='pending')).toHaveLength(0);
 await processIntentJobs(c.db);expect((await service.offers(b.token)).filter(o=>o.status==='pending')).toHaveLength(1);
 expect(await service.respond(b.token,replacements[0]!.publicKey,{action:'accept'})).toMatchObject({status:'accepted'});
});
