import {afterAll,beforeAll,beforeEach,expect,it} from 'vitest';
import {startTestDatabase} from '../support/postgres';
import {applyMigrations} from '@/lib/db/migrations';
import {socialActor,forbiddenKeys} from '../support/social';
import {DiscoveryService} from '@/features/social/discovery';
import {ConnectionsService} from '@/features/social/connections';
import {ConversationService} from '@/features/social/conversations';
import {PlanningService} from '@/features/social/planning';
import {SafetyService} from '@/features/social/safety';
import {NotificationService} from '@/features/notifications/service';
let c:Awaited<ReturnType<typeof startTestDatabase>>;
beforeAll(async()=>{c=await startTestDatabase();await applyMigrations(c.db);});
afterAll(async()=>{if(c)await c.stop();});
beforeEach(async()=>{await c.db.query('TRUNCATE social_profiles CASCADE');});
it('creates transactional deduplicated recipient-only notifications and hides blocked interactions',async()=>{
 const a=await socialActor(c.db,'Private-A'),b=await socialActor(c.db,'Private-B'),x=await socialActor(c.db,'Outsider','INCOGNITO',{activityKey:'football'});
 const cards=await new DiscoveryService(c.db).discover(a.token,a.post.publicKey),connect=new ConnectionsService(c.db),notifications=new NotificationService(c.db);
 const req=await connect.request(a.token,{handle:cards[0]!.handle});await connect.request(a.token,{handle:cards[0]!.handle});
 expect((await notifications.list(b.token)).notifications.map(v=>v.type)).toEqual(['INTEREST_RECEIVED']);
 const match=await connect.respond(b.token,req.publicKey,{action:'accept'});await connect.respond(b.token,req.publicKey,{action:'accept'});
 await new ConversationService(c.db).send(a.token,match.matchKey!,{text:'Private content stays in chat'});
 await new PlanningService(c.db).plan(a.token,match.matchKey!);await new PlanningService(c.db).plan(a.token,match.matchKey!);
 const inbox=await notifications.list(b.token);expect(inbox.notifications.map(v=>v.type)).toEqual(['PLAN_READY','NEW_MESSAGE','INTEREST_RECEIVED']);
 expect((await notifications.list(a.token)).notifications.map(v=>v.type)).toEqual(['PLAN_READY','INTEREST_ACCEPTED']);
 expect(inbox.notifications.filter(n=>n.type!=='INTEREST_RECEIVED').every(n=>n.href===`/m/${match.matchKey}`)).toBe(true);
 expect(forbiddenKeys(inbox)).toEqual([]);expect(JSON.stringify(inbox)).not.toMatch(/Private content|Private-A|Private-B/);
 expect(await notifications.unread(b.token)).toEqual({unreadCount:3,capped:false});
 await expect(notifications.read(x.token,inbox.notifications[0]!.publicKey)).rejects.toMatchObject({code:'NOT_FOUND'});
 await notifications.read(b.token,inbox.notifications[0]!.publicKey);expect((await notifications.unread(b.token)).unreadCount).toBe(2);
 await new SafetyService(c.db).block(a.token,{matchKey:match.matchKey!});
 expect((await notifications.list(b.token)).notifications).toEqual([]);expect((await notifications.unread(b.token)).unreadCount).toBe(0);
});
