import {readAggregateFunnel} from '@/lib/analytics/funnel-report';
import { afterAll,beforeAll,beforeEach,expect,it } from 'vitest';
import {startTestDatabase} from '../support/postgres';
import {applyMigrations} from '@/lib/db/migrations';
import {socialActor,seekingInput} from '../support/social';
import {SeekingService} from '@/features/social/seeking';
import {DiscoveryService} from '@/features/social/discovery';
import {ConnectionsService} from '@/features/social/connections';
import {ConversationService} from '@/features/social/conversations';
import {PlanningService} from '@/features/social/planning';
import {trackFunnel} from '@/lib/analytics/funnel';
let c:Awaited<ReturnType<typeof startTestDatabase>>;
beforeAll(async()=>{c=await startTestDatabase();await applyMigrations(c.db);});
afterAll(async()=>{if(c)await c.stop();});
beforeEach(async()=>{await c.db.query('TRUNCATE social_profiles,analytics_events CASCADE');});
it('records committed server transitions once without personal payloads or client identifiers',async()=>{
 const a=await socialActor(c.db,'Analytics-A'),b=await socialActor(c.db,'Analytics-B');
 await c.db.query('TRUNCATE seeking_posts CASCADE');
 const options={analyticsEnabled:true};
 const seek=new SeekingService(c.db,options);
 const pa=await seek.create(a.token,seekingInput()),pb=await seek.create(b.token,seekingInput());expect(pb.publicKey).toBeTruthy();
 const discover=new DiscoveryService(c.db,options);
 const cards=await discover.discover(a.token,pa.publicKey);await discover.discover(a.token,pa.publicKey);
 const connect=new ConnectionsService(c.db,options);
 const request=await connect.request(a.token,{handle:cards[0]!.handle});await connect.request(a.token,{handle:cards[0]!.handle});
 const accepted=await connect.respond(b.token,request.publicKey,{action:'accept'});await connect.respond(b.token,request.publicKey,{action:'accept'});
 const chat=new ConversationService(c.db,options);
 await chat.send(a.token,accepted.matchKey!,{text:'Never analytics content'});await chat.send(b.token,accepted.matchKey!,{text:'Second message'});
 const plan=new PlanningService(c.db,options);await plan.plan(a.token,accepted.matchKey!);await plan.plan(a.token,accepted.matchKey!);
 const counts=(await c.db.query<{event_name:string;n:number}>("SELECT event_name,count(*)::int AS n FROM analytics_events WHERE surface='social' GROUP BY event_name")).rows;
 expect(Object.fromEntries(counts.map(v=>[v.event_name,v.n]))).toEqual({seeking_created:2,discovery_results_seen:1,interest_sent:1,interest_received:1,match_created:1,first_message_sent:1,plan_created:1});
 expect(await readAggregateFunnel(c.db,7)).toEqual({days:7,seeking:2,candidates:1,interested:1,matches:1,conversations:1,plans:1,confirmed:0});
 await expect(readAggregateFunnel(c.db,31)).rejects.toThrow();
 const fields=(await c.db.query<{column_name:string}>("SELECT column_name FROM information_schema.columns WHERE table_name='analytics_events' ORDER BY ordinal_position")).rows.map(v=>v.column_name);
 expect(fields).toEqual(['id','event_name','surface','created_at']);
});
it('disabled analytics never persists even a valid funnel transition',async()=>{
 await trackFunnel(c.db,'seeking_created',false);expect((await c.db.query('SELECT * FROM analytics_events')).rows).toEqual([]);
 await expect(trackFunnel(c.db,'bogus' as never,true)).rejects.toThrow();expect((await c.db.query('SELECT * FROM analytics_events')).rows).toEqual([]);
});
