import { afterAll, beforeAll, beforeEach, expect, it } from 'vitest';
import { startTestDatabase } from '../support/postgres';
import { applyMigrations } from '@/lib/db/migrations';
import { socialActor, forbiddenKeys } from '../support/social';
import { DiscoveryService } from '@/features/social/discovery';
import { ConnectionsService } from '@/features/social/connections';
import { ConversationService } from '@/features/social/conversations';
import { PlanningService } from '@/features/social/planning';
import { SafetyService } from '@/features/social/safety';
import { requireProfile } from '@/features/social/context';
import { readSocialEvents } from '@/features/realtime/events';
let c: Awaited<ReturnType<typeof startTestDatabase>>;
beforeAll(async()=>{c=await startTestDatabase();await applyMigrations(c.db);});
afterAll(async()=>{if(c) await c.stop();});
beforeEach(async()=>{await c.db.query('TRUNCATE social_profiles CASCADE');});
it('persists recipient-owned invalidations for every committed connection/chat/plan/block change',async()=>{
 const a=await socialActor(c.db,'Hidden-A'),b=await socialActor(c.db,'Hidden-B'),x=await socialActor(c.db,'Outsider','INCOGNITO',{activityKey:'football',activityLabel:'Football'});
 const profiles=await c.db.transaction(async tx=>{const result=[];for(const v of [a,b,x])result.push(await requireProfile(tx,v.token));return result;});
 const cards=await new DiscoveryService(c.db).discover(a.token,a.post.publicKey);
 const target=b;
 const targetId=profiles[1]!.id;
 const connections=new ConnectionsService(c.db),chat=new ConversationService(c.db);
 const request=await connections.request(a.token,{handle:cards[0]!.handle});
 const before=(await readSocialEvents(c.db,targetId)).events;
 expect(before.map(v=>v.topic)).toContain('connections');
 await connections.request(a.token,{handle:cards[0]!.handle});
 expect((await readSocialEvents(c.db,targetId)).events).toEqual(before);
 const accepted=await connections.respond(target.token,request.publicKey,{action:'accept'});
 expect(accepted.matchKey).toBeTruthy();
 const key=accepted.matchKey!;
 await chat.send(a.token,key,{text:'Private message never belongs in events'});
 await chat.disclose(target.token,key,{kind:'first_name',value:'Private name',consent:true});
 await new PlanningService(c.db).plan(a.token,key);
 const events=(await readSocialEvents(c.db,targetId)).events;
 expect(events.filter(v=>v.topic==='match').length).toBeGreaterThanOrEqual(4);
 expect(events.filter(v=>v.topic==='match').every(v=>v.matchKey===key)).toBe(true);
 expect(forbiddenKeys(events)).toEqual([]);
 expect(JSON.stringify(events)).not.toMatch(/Hidden-|Private message|Private name/);
 await new SafetyService(c.db).block(a.token,{matchKey:key});
 const closed=(await readSocialEvents(c.db,targetId)).events;
 expect(closed.at(-1)!.topic).toBe('match');
 expect(closed.slice(-3).map(v=>v.topic)).toEqual(['notifications','connections','match']);
 expect(closed.every(v=>v.matchKey===undefined)).toBe(true);
 await expect(chat.send(target.token,key,{text:'blocked'})).rejects.toMatchObject({code:'CONFLICT'});
});
